defaults:
  - sdg_text_davinci_003_pc

data_dir: ${data_dir}/processed/${.name}

filter_on_num_tokens: True
apply_ordering_heuristic: False # We will load a dataset that is already ordered
gzipped: True

dataset_parameters:
  train:
    dataset:
      load_dataset_params:
        split: "test_ordered"
  val:
    dataset:
      load_dataset_params:
        split: "test_ordered"
  test:
    dataset:
      load_dataset_params:
        split: "test_ordered"
